import {
  Activity,
  BadgeCheck,
  BadgePercent,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardCheck,
  ClipboardList,
  CloudCog,
  Contact,
  CreditCard,
  Crown,
  Factory,
  FileBarChart,
  FileKey2,
  FileText,
  Flag,
  Gauge,
  Gift,
  Globe2,
  HandCoins,
  Headphones,
  HeartHandshake,
  IdCard,
  KeyRound,
  Landmark,
  Layers3,
  LifeBuoy,
  Mail,
  MapPinned,
  Megaphone,
  MessageCircle,
  NotebookText,
  Package,
  PackageCheck,
  PackageOpen,
  PackageSearch,
  PanelTop,
  QrCode,
  RefreshCcw,
  ScanLine,
  ScanSearch,
  SearchCheck,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Stars,
  Store,
  Tags,
  Target,
  TicketPercent,
  Truck,
  UserCheck,
  UserCog,
  Users,
  UsersRound,
  WalletCards,
  Warehouse,
  Webhook,
  Wrench,
} from "lucide-react";
import type { SidebarGroup, SidebarItem, EnterpriseRoute } from "../types/navigation";

const item = (
  id: string,
  title: string,
  icon: SidebarItem["icon"],
  route: string,
  permission: string,
  children: SidebarItem[] = [],
): SidebarItem => ({ id, title, icon, route, permission, children });

export const sidebarItems: SidebarGroup[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    items: [
      item("manufacturer-executive-dashboard", "Executive Dashboard", Gauge, "/dashboard", "manufacturer.dashboard.executive.view"),
      item("manufacturer-ai-dashboard", "AI Dashboard", BrainCircuit, "/ai-dashboard", "manufacturer.dashboard.ai.view"),
      item("manufacturer-my-tasks", "My Tasks", ClipboardCheck, "/tasks", "manufacturer.dashboard.tasks.view"),
      item("manufacturer-notifications", "Notifications", Bell, "/notifications", "manufacturer.dashboard.notifications.view"),
      item("manufacturer-recent-activities", "Recent Activities", Activity, "/recent-activities", "manufacturer.dashboard.activities.view"),
    ],
  },
  {
    id: "organization",
    title: "Organization",
    items: [
      item("company-profile", "Company Profile", Building2, "/company-profile", "organization.company_profile.view"),
      item("users", "Users", Users, "/users", "organization.users.view"),
      item("departments", "Departments", Building2, "/departments", "organization.departments.view"),
      item("teams", "Teams", UsersRound, "/teams", "organization.teams.view"),
      item("roles", "Roles", UserCog, "/roles", "organization.roles.view"),
      item("permissions", "Permissions", KeyRound, "/permissions", "organization.permissions.view"),
      item("audit-logs", "Audit Logs", FileText, "/audit-logs", "organization.audit_logs.view"),
    ],
  },
  {
    id: "master-data",
    title: "Master Data",
    items: [
      item("categories", "Categories", Tags, "/categories", "master_data.categories.view"),
      item("brands", "Brands", BadgeCheck, "/brands", "master_data.brands.view"),
      item("products", "Products", Package, "/products", "master_data.products.view"),
      item("sku-management", "SKU Management", Boxes, "/sku-management", "master_data.sku.view"),
      item("product-attributes", "Product Attributes", Layers3, "/product-attributes", "master_data.product_attributes.view"),
      item("price-lists", "Price Lists", HandCoins, "/price-lists", "master_data.price_lists.view"),
      item("units", "Units", PackageCheck, "/units", "master_data.units.view"),
      item("tax", "Tax", CreditCard, "/tax", "master_data.tax.view"),
      item("hsn-codes", "HSN Codes", FileKey2, "/hsn-codes", "master_data.hsn_codes.view"),
    ],
  },
  {
    id: "manufacturing",
    title: "Manufacturing",
    items: [
      item("factory", "Factories", Factory, "/factory", "manufacturing.factories.view"),
      item("production-orders", "Production Orders", ClipboardList, "/production-orders", "manufacturing.production_orders.view"),
      item("production-lines", "Production Lines", Layers3, "/production-lines", "manufacturing.production_lines.view"),
      item("machines", "Machines", Wrench, "/machines", "manufacturing.machines.view"),
      item("operators", "Operators", UserCheck, "/operators", "manufacturing.operators.view"),
      item("shifts", "Shifts", CalendarDays, "/shifts", "manufacturing.shifts.view"),
      item("quality-control", "Quality Control", ClipboardCheck, "/quality-control", "manufacturing.quality_control.view"),
      item("rejected-products", "Rejected Products", PackageOpen, "/rejected-products", "manufacturing.rejected_products.view"),
      item("scrapped-batches", "Scrapped Products", PackageOpen, "/scrapped-batches", "manufacturing.scrapped_products.view"),
    ],
  },
  {
    id: "inventory",
    title: "Inventory",
    items: [
      item("warehouse", "Warehouses", Warehouse, "/warehouse", "inventory.warehouses.view"),
      item("bins", "Bins", Boxes, "/bins", "inventory.bins.view"),
      item("inventory", "Inventory", PackageSearch, "/inventory", "inventory.stock.view"),
      item("stock-movement", "Stock Movement", RefreshCcw, "/inventory/movements", "inventory.stock_movement.view"),
      item("inbound", "Inbound", PackageCheck, "/inbound", "inventory.inbound.view"),
      item("outbound", "Outbound", Truck, "/outbound", "inventory.outbound.view"),
      item("transfers", "Transfers", RefreshCcw, "/transfers", "inventory.transfers.view"),
      item("warehouse-returns", "Returns", PackageOpen, "/returns", "inventory.returns.view"),
      item("cycle-count", "Cycle Count", ClipboardCheck, "/cycle-count", "inventory.cycle_count.view"),
    ],
  },
  {
    id: "qr-platform",
    title: "QR Platform",
    items: [
      item("qr-dashboard", "QR Dashboard", QrCode, "/qr/dashboard", "qr.dashboard.view"),
      item("qr-batches", "QR Batches", Layers3, "/qr/batches", "qr.batches.view"),
      item("qr-generate", "Generate QR", QrCode, "/qr/generate", "qr.generate.view"),
      item("qr-codes", "QR Codes", ScanLine, "/qr/codes", "qr.codes.view"),
      item("qr-analytics", "QR Analytics", BarChart3, "/qr/analytics", "qr.analytics.view"),
      item("gs1-digital-links", "GS1 Digital Links", Globe2, "/gs1", "qr.gs1.view"),
      item("aggregation", "Aggregation", Layers3, "/aggregation", "qr.aggregation.view"),
      item("print-queue", "Print Queue", FileText, "/print", "qr.print_queue.view"),
      item("qr-security", "QR Security", ShieldCheck, "/security", "qr.security.view"),
      item("scan-logs", "Scan Logs", ScanSearch, "/scan-logs", "qr.scan_logs.view"),
      item("qr-templates", "QR Templates", PanelTop, "/qr/templates", "qr.templates.view"),
    ],
  },
  {
    id: "supply-chain",
    title: "Supply Chain",
    items: [
      item("distributors", "Distributors", Truck, "/distributors", "supply_chain.distributors.view"),
      item("dealers", "Dealers", Store, "/dealers", "supply_chain.dealers.view"),
      item("retailers", "Retailers", ShoppingBag, "/retailers", "supply_chain.retailers.view"),
      item("contractors", "Contractors", Wrench, "/contractors", "supply_chain.contractors.view"),
      item("orders", "Orders", ClipboardList, "/orders", "supply_chain.orders.view"),
      item("dispatch", "Dispatch", MapPinned, "/dispatch", "supply_chain.dispatch.view"),
      item("shipments", "Shipments", PackageCheck, "/shipments", "supply_chain.shipments.view"),
      item("returns", "Returns", RefreshCcw, "/returns", "supply_chain.returns.view"),
    ],
  },
  {
    id: "customers",
    title: "Customers",
    items: [
      item("customers", "Customers", Users, "/customers", "customers.list.view"),
      item("customer-360", "Customer 360", Contact, "/customer-360", "customers.customer_360.view"),
      item("customer-wallet", "Wallet", WalletCards, "/customer-wallet", "customers.wallet.view"),
      item("customer-rewards", "Rewards", Gift, "/customer-rewards", "customers.rewards.view"),
      item("customer-scans", "Scans", ScanSearch, "/customer-scans", "customers.scans.view"),
      item("warranty", "Warranty", ShieldCheck, "/customer-warranty", "customers.warranty.view"),
      item("customer-projects", "Projects", BriefcaseBusiness, "/customer-projects", "customers.projects.view"),
      item("support", "Support", LifeBuoy, "/customer-support-portal", "customers.support.view"),
      item("customer-referrals", "Referral", HeartHandshake, "/customer-referrals", "customers.referral.view"),
    ],
  },
  {
    id: "crm",
    title: "CRM",
    items: [
      item("leads", "Leads", Target, "/leads", "crm.leads.view"),
      item("accounts", "Accounts", Landmark, "/accounts", "crm.accounts.view"),
      item("contacts", "Contacts", Contact, "/contacts", "crm.contacts.view"),
      item("pipeline", "Pipeline", ChartNoAxesCombined, "/opportunities", "crm.pipeline.view"),
      item("meetings", "Meetings", UsersRound, "/meetings", "crm.meetings.view"),
      item("calendar", "Calendar", CalendarDays, "/calendar", "crm.calendar.view"),
      item("tasks", "Tasks", ClipboardCheck, "/tasks", "crm.tasks.view"),
      item("notes", "Notes", NotebookText, "/notes", "crm.notes.view"),
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    items: [
      item("campaigns", "Campaigns", Megaphone, "/campaigns", "marketing.campaigns.view"),
      item("landing-pages", "Landing Pages", PanelTop, "/landing-pages", "marketing.landing_pages.view"),
      item("coupons", "Coupons", TicketPercent, "/coupons", "marketing.coupons.view"),
      item("scratch-cards", "Scratch Cards", Stars, "/scratch-cards", "marketing.scratch_cards.view"),
      item("spin-wheel", "Spin Wheel", BadgePercent, "/spin-wheel", "marketing.spin_wheel.view"),
      item("whatsapp-campaigns", "WhatsApp", MessageCircle, "/whatsapp", "marketing.whatsapp.view"),
      item("email-campaigns", "Email", Mail, "/email", "marketing.email.view"),
      item("push-notifications", "Push Notifications", Bell, "/push", "marketing.push.view"),
      item("automation", "Automation", Sparkles, "/automation", "marketing.automation.view"),
      item("segments", "Segments", UsersRound, "/segments", "marketing.segments.view"),
      item("surveys", "Surveys", ClipboardList, "/surveys", "marketing.surveys.view"),
    ],
  },
  {
    id: "loyalty",
    title: "Loyalty",
    items: [
      item("loyalty-wallet", "Wallet", WalletCards, "/loyalty/wallet", "loyalty.wallet.view"),
      item("points-engine", "Reward Rules", HandCoins, "/points-engine", "loyalty.reward_rules.view"),
      item("rewards-catalog", "Rewards Catalog", Gift, "/rewards-catalog", "loyalty.rewards_catalog.view"),
      item("cashback", "Cashback", CreditCard, "/cashback", "loyalty.cashback.view"),
      item("membership-tiers", "Membership Tiers", IdCard, "/membership-tiers", "loyalty.membership_tiers.view"),
      item("leaderboards", "Leaderboards", Crown, "/leaderboards", "loyalty.leaderboards.view"),
      item("achievements", "Achievements", BadgeCheck, "/achievements", "loyalty.achievements.view"),
      item("redemptions", "Redemptions", Gift, "/redemptions", "loyalty.redemptions.view"),
    ],
  },
  {
    id: "warranty-service",
    title: "Warranty & Service",
    items: [
      item("service-warranty", "Warranty", ShieldCheck, "/warranty", "service.warranty.view"),
      item("warranty-claims", "Claims", ClipboardList, "/warranty-claims", "service.claims.view"),
      item("service-requests", "Service Requests", Headphones, "/service-requests", "service.requests.view"),
      item("amc", "AMC", BadgeCheck, "/amc", "service.amc.view"),
      item("rma", "RMA", RefreshCcw, "/rma", "service.rma.view"),
      item("technicians", "Technicians", Wrench, "/technicians", "service.technicians.view"),
      item("helpdesk", "Helpdesk", LifeBuoy, "/helpdesk", "service.helpdesk.view"),
    ],
  },
  {
    id: "finance",
    title: "Finance",
    items: [
      item("invoices", "Invoices", FileText, "/invoices", "finance.invoices.view"),
      item("payments", "Payments", CreditCard, "/payments", "finance.payments.view"),
      item("subscriptions", "Subscriptions", BadgeCheck, "/subscriptions", "finance.subscriptions.view"),
      item("gst", "GST", Landmark, "/gst", "finance.gst.view"),
      item("expenses", "Expenses", HandCoins, "/expenses", "finance.expenses.view"),
      item("finance-reports", "Finance Reports", FileBarChart, "/finance-reports", "finance.reports.view"),
    ],
  },
  {
    id: "reports",
    title: "Reports",
    items: [
      item("sales-reports", "Sales Reports", FileBarChart, "/reports/sales", "reports.sales.view"),
      item("inventory-reports", "Inventory Reports", FileBarChart, "/reports/inventory", "reports.inventory.view"),
      item("qr-reports", "QR Reports", QrCode, "/reports/qr", "reports.qr.view"),
      item("customer-reports", "Customer Reports", Users, "/reports/customer", "reports.customer.view"),
      item("dealer-reports", "Dealer Reports", Store, "/reports/dealer", "reports.dealer.view"),
      item("campaign-reports", "Campaign Reports", Megaphone, "/reports/campaign", "reports.campaign.view"),
      item("warranty-reports", "Warranty Reports", ShieldCheck, "/reports/warranty", "reports.warranty.view"),
      item("report-finance-reports", "Finance Reports", CreditCard, "/reports/financial", "reports.finance.view"),
      item("export-center", "Export Center", FileText, "/export-center", "reports.export_center.view"),
    ],
  },
  {
    id: "ai",
    title: "AI",
    items: [
      item("ai-dashboard", "AI Dashboard", BrainCircuit, "/ai", "ai.dashboard.view"),
      item("fraud-detection", "Fraud Detection", SearchCheck, "/fraud-detection", "ai.fraud_detection.view"),
      item("forecasting", "Forecasting", Activity, "/forecasting", "ai.forecasting.view"),
      item("ocr", "OCR", ScanSearch, "/ocr", "ai.ocr.view"),
      item("recommendations", "Recommendations", Sparkles, "/recommendations", "ai.recommendations.view"),
      item("ai-assistant", "AI Assistant", Bot, "/ai-assistant", "ai.assistant.view"),
      item("model-management", "Model Management", BrainCircuit, "/ai-models", "ai.model_management.view"),
    ],
  },
  {
    id: "settings",
    title: "Settings",
    items: [
      item("company-settings", "Company Settings", Settings, "/company-settings", "settings.company.view"),
      item("branding", "Branding", BadgePercent, "/branding", "settings.branding.view"),
      item("white-label", "White Label", Stars, "/white-label", "settings.white_label.view"),
      item("domains", "Domains", Globe2, "/domains", "settings.domains.view"),
      item("smtp", "SMTP", Mail, "/smtp", "settings.smtp.view"),
      item("sms", "SMS", MessageCircle, "/sms", "settings.sms.view"),
      item("whatsapp", "WhatsApp", MessageCircle, "/whatsapp", "settings.whatsapp.view"),
      item("api-keys", "API Keys", FileKey2, "/api-keys", "settings.api_keys.view"),
      item("webhooks", "Webhooks", Webhook, "/webhooks", "settings.webhooks.view"),
      item("security", "Security", ShieldCheck, "/security", "settings.security.view"),
      item("developer-settings", "Developer Settings", CloudCog, "/developer-settings", "settings.developer.view"),
    ],
  },
];

const flattenItems = (items: SidebarItem[]): SidebarItem[] =>
  items.flatMap((navItem) => [navItem, ...flattenItems(navItem.children)]);

export const flatSidebarItems: SidebarItem[] = sidebarItems.flatMap((group) =>
  flattenItems(group.items),
);

export const enterpriseRoutes: EnterpriseRoute[] = sidebarItems.flatMap((group) =>
  flattenItems(group.items).flatMap((navItem) => [
    {
      id: navItem.id,
      title: navItem.title,
      route: navItem.route,
      permission: navItem.permission,
      group: group.title,
      icon: navItem.icon,
      mode: "list" as const,
    },
    {
      id: `${navItem.id}-create`,
      title: `Create ${navItem.title}`,
      route: `${navItem.route}/create`,
      permission: navItem.permission.replace(".view", ".create"),
      group: group.title,
      icon: navItem.icon,
      mode: "create" as const,
    },
    {
      id: `${navItem.id}-detail`,
      title: `${navItem.title} Details`,
      route: `${navItem.route}/:id`,
      permission: navItem.permission,
      group: group.title,
      icon: navItem.icon,
      mode: "detail" as const,
    },
  ]),
);
